#  https://console.aiven.io/account/a5b9ec10a03b/project/e-skate/services/mysql-1844e9d9/settings

spring:
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_68qA3_0yUlwb5NE2N_e@mysql-1844e9d9-e-skate.a.aivencloud.com:13926/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_68qA3_0yUlwb5NE2N_e
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
#    drop-first: true
  security:
    user:
      name: admin
      password: admin

cors:
  allowedOrigins: http://localhost:4200

springdoc:
  api-docs:
    enabled: true
#
#server:
#  address: 192.168.1.88
#  port: 443
#  ssl:
#    enabled: true
#    key-store: classpath:keystoreTLS.p12
#    key-store-password: 111111
#    key-store-type: PKCS12
#    key-alias: springboot
